// rilidata.js - 365天灵感日历数据
const riliData = {
    // 1月
    "1-1": { event: "晨跑", pinyin: "chen pao", quote: "迎着第一缕阳光，脚步丈量梦想的距离。" },
    "1-2": { event: "读书", pinyin: "du shu", quote: "翻开书页，与千年智者对话。" },
    "1-3": { event: "冥想", pinyin: "ming xiang", quote: "闭上眼睛，才能看见内心的星空。" },
    "1-4": { event: "写信", pinyin: "xie xin", quote: "笔尖流淌的不只是墨水，还有思念。" },
    "1-5": { event: "品茶", pinyin: "pin cha", quote: "一盏清茶，洗去岁月的浮躁。" },
    "1-6": { event: "做饭", pinyin: "zuo fan", quote: "烟火气，才是生活最动人的底色。" },
    "1-7": { event: "遛狗", pinyin: "liu gou", quote: "狗狗教会我们，简单也是一种幸福。" },
    "1-8": { event: "画画", pinyin: "hua hua", quote: "画笔下，世界因你的视角而独特。" },
    "1-9": { event: "听雨", pinyin: "ting yu", quote: "雨滴敲窗，大自然的心跳声。" },
    "1-10": { event: "看展", pinyin: "kan zhan", quote: "艺术不是孤岛，是心灵的桥梁。" },
    "1-11": { event: "整理", pinyin: "zheng li", quote: "断舍离，为心灵腾出生长的空间。" },
    "1-12": { event: "散步", pinyin: "san bu", quote: "慢下来，才能看见生活的细节。" },
    "1-13": { event: "手账", pinyin: "shou zhang", quote: "记录生活，是与未来的自己对话。" },
    "1-14": { event: "追剧", pinyin: "zhui ju", quote: "他人的故事，照亮我们的人生。" },
    "1-15": { event: "做梦", pinyin: "zuo meng", quote: "梦想是心灵的罗盘，指引前行方向。" },
    "1-16": { event: "赏月", pinyin: "shang yue", quote: "仰望月色，与古人共赏一轮明月。" },
    "1-17": { event: "露营", pinyin: "lu ying", quote: "星空为被，大地为床，回归自然的怀抱。" },
    "1-18": { event: "摄影", pinyin: "she ying", quote: "按下快门，凝固时光中最美的瞬间。" },
    "1-19": { event: "烘焙", pinyin: "hong bei", quote: "揉进面团的，是等待的艺术。" },
    "1-20": { event: "植物", pinyin: "zhi wu", quote: "照顾一株植物，也是照顾自己的心情。" },
    "1-21": { event: "音乐", pinyin: "yin yue", quote: "音符是情感的符号，跳动心灵的律动。" },
    "1-22": { event: "手工", pinyin: "shou gong", quote: "双手创造，赋予物品温度与灵魂。" },
    "1-23": { event: "沐浴", pinyin: "mu yu", quote: "水流带走疲惫，留下身心的轻盈。" },
    "1-24": { event: "早起", pinyin: "zao qi", quote: "清晨的宁静，是送给自己的礼物。" },
    "1-25": { event: "慢跑", pinyin: "man pao", quote: "每一步都是坚持，汗水浇灌收获。" },
    "1-26": { event: "瑜伽", pinyin: "yu jia", quote: "身体的柔软，源于心灵的舒展。" },
    "1-27": { event: "冲咖", pinyin: "chong ka", quote: "一杯咖啡，唤醒沉睡的灵感。" },
    "1-28": { event: "观影", pinyin: "guan ying", quote: "银幕上的人生百态，照见内心的自己。" },
    "1-29": { event: "发呆", pinyin: "fa dai", quote: "发呆也是生产力，让思绪自由飞翔。" },
    "1-30": { event: "收纳", pinyin: "shou na", quote: "整理空间，也是整理思绪。" },
    "1-31": { event: "闲聊", pinyin: "xian liao", quote: "平凡对话中，藏着生活的智慧。" },

    // 2月
    "2-1": { event: "折纸", pinyin: "zhe zhi", quote: "一张纸的千变万化，源于匠心独运。" },
    "2-2": { event: "赏花", pinyin: "shang hua", quote: "花开不语，却道尽生命的绚烂。" },
    "2-3": { event: "写诗", pinyin: "xie shi", quote: "诗意栖居，让平凡生活披上华丽外衣。" },
    "2-4": { event: "弹琴", pinyin: "tan qin", quote: "十指流淌的音符，是心灵的独白。" },
    "2-5": { event: "刺绣", pinyin: "ci xiu", quote: "一针一线，绣出生活的细腻与耐心。" },
    "2-6": { event: "养鱼", pinyin: "yang yu", quote: "鱼儿悠然，教会我们宁静的智慧。" },
    "2-7": { event: "做梦", pinyin: "zuo meng", quote: "梦想是心灵的灯塔，照亮前行的路。" },
    "2-8": { event: "看云", pinyin: "kan yun", quote: "云卷云舒，人生亦当如此从容。" },
    "2-9": { event: "品酒", pinyin: "pin jiu", quote: "酒入愁肠，化作相思泪。" },
    "2-10": { event: "拼图", pinyin: "pin tu", quote: "生活如拼图，耐心拼凑才见全貌。" },
    "2-11": { event: "冥想", pinyin: "ming xiang", quote: "静坐常思己过，闲谈莫论人非。" },
    "2-12": { event: "做糕", pinyin: "zuo gao", quote: "甜点的秘诀：耐心等待，恰到好处。" },
    "2-13": { event: "看雪", pinyin: "kan xue", quote: "雪花的旅程，是从天堂到人间。" },
    "2-14": { event: "送礼", pinyin: "song li", quote: "礼物包裹的，是看不见的牵挂。" },
    "2-15": { event: "观星", pinyin: "guan xing", quote: "仰望星空，才知人类渺小而伟大。" },
    "2-16": { event: "剪纸", pinyin: "jian zhi", quote: "剪刀下的艺术，是中国人的巧思。" },
    "2-17": { event: "煮茶", pinyin: "zhu cha", quote: "一壶好茶，温暖整个冬天。" },
    "2-18": { event: "赏雪", pinyin: "shang xue", quote: "雪是大地的梦，纯白无瑕。" },
    "2-19": { event: "速写", pinyin: "su xie", quote: "笔下生花，定格世界的瞬息万变。" },
    "2-20": { event: "做面", pinyin: "zuo mian", quote: "和面如修行，需要耐心与专注。" },
    "2-21": { event: "看书", pinyin: "kan shu", quote: "读书破万卷，下笔如有神。" },
    "2-22": { event: "写字", pinyin: "xie zi", quote: "字如其人，笔墨间见修养。" },
    "2-23": { event: "听风", pinyin: "ting feng", quote: "风声里，藏着大自然的密语。" },
    "2-24": { event: "赏景", pinyin: "shang jing", quote: "美景在心，不在远方。" },
    "2-25": { event: "做菜", pinyin: "zuo cai", quote: "食材的灵魂，在于烹饪者的用心。" },
    "2-26": { event: "修禅", pinyin: "xiu chan", quote: "禅修不在庙宇，在于心的澄明。" },
    "2-27": { event: "品茗", pinyin: "pin ming", quote: "茶香入喉，岁月静好。" },
    "2-28": { event: "看海", pinyin: "kan hai", quote: "面朝大海，心向春暖花开。" },
    "2-29": { event: "放风", pinyin: "fang feng", quote: "风筝飞得再高，也放不断那根线。" },
    "3-1": { "event": "踏青", "pinyin": "ta qing", "quote": "春风十里，不如与你同行。" },
    "3-2": { "event": "赏春", "pinyin": "shang chun", "quote": "春天是一首诗，写满希望与生机。" },
    "3-3": { "event": "植树", "pinyin": "zhi shu", "quote": "种下一棵树，就是种下未来。" },
    "3-4": { "event": "放风", "pinyin": "fang feng", "quote": "风筝飞上天，牵着地上的思念。" },
    "3-5": { "event": "春游", "pinyin": "chun you", "quote": "春光不必趁早，但请勿虚度。" },
    "3-6": { "event": "画眉", "pinyin": "hua mei", "quote": "眉如远山，画出心中的风景。" },
    "3-7": { "event": "拍照", "pinyin": "pai zhao", "quote": "镜头里的春天，定格生命的律动。" },
    "3-8": { "event": "野餐", "pinyin": "ye can", "quote": "草地上的午餐，味蕾与自然的对话。" },
    "3-9": { "event": "赏樱", "pinyin": "shang ying", "quote": "樱花短暂而绚烂，如同青春。" },
    "3-10": { "event": "春跑", "pinyin": "chun pao", "quote": "春风拂面，奔向更好的自己。" },
    "3-11": { "event": "踢球", "pinyin": "ti qiu", "quote": "足球场上，释放激情与活力。" },
    "3-12": { "event": "放船", "pinyin": "fang chuan", "quote": "扬帆起航，驶向梦想的彼岸。" },
    "3-13": { "event": "钓鱼", "pinyin": "diao yu", "quote": "垂钓是一场与自己的对话。" },
    "3-14": { "event": "春唱", "pinyin": "chun chang", "quote": "歌声里，绽放内心的春天。" },
    "3-15": { "event": "赏鸟", "pinyin": "shang niao", "quote": "鸟语花香，春天最美的交响曲。" },
    "3-16": { "event": "春读", "pinyin": "chun du", "quote": "春光里读书，别有一番滋味。" },
    "3-17": { "event": "春写", "pinyin": "chun xie", "quote": "春天的文字，饱含生命力。" },
    "3-18": { "event": "春画", "pinyin": "chun hua", "quote": "画笔下的春天，永不凋零。" },
    "3-19": { "event": "春思", "pinyin": "chun si", "quote": "春天里的思绪，如花般绽放。" },
    "3-20": { "event": "春忆", "pinyin": "chun yi", "quote": "回忆是春风，轻抚心灵的褶皱。" },
    "3-21": { "event": "春望", "pinyin": "chun wang", "quote": "登高望远，心胸如春天般开阔。" },
    "3-22": { "event": "春耕", "pinyin": "chun geng", "quote": "春种一粒粟，秋收万颗子。" },
    "3-23": { "event": "春茶", "pinyin": "chun cha", "quote": "一杯春茶，品味节气更迭。" },
    "3-24": { "event": "春酒", "pinyin": "chun jiu", "quote": "春酒醉人，不如春光醉人。" },
    "3-25": { "event": "春梦", "pinyin": "chun meng", "quote": "春梦如诗，醒来依然美好。" },
    "3-26": { "event": "春雨", "pinyin": "chun yu", "quote": "春雨贵如油，滋润万物生长。" },
    "3-27": { "event": "春风", "pinyin": "chun feng", "quote": "春风得意马蹄疾，一日看尽长安花。" },
    "3-28": { "event": "春晓", "pinyin": "chun xiao", "quote": "春眠不觉晓，处处闻啼鸟。" },
    "3-29": { "event": "春行", "pinyin": "chun xing", "quote": "行走在春天，每一步都是诗意。" },
    "3-30": { "event": "春意", "pinyin": "chun yi", "quote": "春意盎然，如你眼中的笑意。" },
    "3-31": { "event": "春歌", "pinyin": "chun ge", "quote": "春天的歌谣，唱不尽的美好。" },

    "4-1": { "event": "愚人", "pinyin": "yu ren", "quote": "偶尔恶作剧，增添生活乐趣。" },
    "4-2": { "event": "清明", "pinyin": "qing ming", "quote": "慎终追远，民族的情感寄托。" },
    "4-3": { "event": "放纸", "pinyin": "fang zhi", "quote": "纸鸢高飞，思念亦飞扬。" },
    "4-4": { "event": "扫墓", "pinyin": "sao mu", "quote": "缅怀先人，感恩生活。" },
    "4-5": { "event": "踏青", "pinyin": "ta qing", "quote": "青山绿水间，寻找内心平静。" },
    "4-6": { "event": "赏花", "pinyin": "shang hua", "quote": "花开花落，人生亦如此。" },
    "4-7": { "event": "春游", "pinyin": "chun you", "quote": "行走在春天里，感受生命力量。" },
    "4-8": { "event": "植树", "pinyin": "zhi shu", "quote": "种下一棵树，就是种下希望。" },
    "4-9": { "event": "野炊", "pinyin": "ye chui", "quote": "户外烹饪，别有一番风味。" },
    "4-10": { "event": "春浴", "pinyin": "chun yu", "quote": "沐浴春风，洗去冬日疲惫。" },
    "4-11": { "event": "春晒", "pinyin": "chun shai", "quote": "晒太阳，晒心情。" },
    "4-12": { "event": "春眠", "pinyin": "chun mian", "quote": "春困袭来，小憩片刻。" },
    "4-13": { "event": "春笑", "pinyin": "chun xiao", "quote": "笑口常开，春暖花开。" },
    "4-14": { "event": "春语", "pinyin": "chun yu", "quote": "春天的语言，写在花瓣上。" },
    "4-15": { "event": "春绘", "pinyin": "chun hui", "quote": "绘春天之美，留心中之景。" },
    "4-16": { "event": "春诵", "pinyin": "chun song", "quote": "诵读春天的诗篇。" },
    "4-17": { "event": "春拍", "pinyin": "chun pai", "quote": "拍下春天，留住美好。" },
    "4-18": { "event": "春染", "pinyin": "chun ran", "quote": "春天的色彩，染红了世界。" },
    "4-19": { "event": "春织", "pinyin": "chun zhi", "quote": "编织春天的梦想。" },
    "4-20": { "event": "春品", "pinyin": "chun pin", "quote": "品味春天的气息。" },
    "4-21": { "event": "春吟", "pinyin": "chun yin", "quote": "吟诵春天的诗歌。" },
    "4-22": { "event": "春舞", "pinyin": "chun wu", "quote": "舞动春天的节奏。" },
    "4-23": { "event": "春弈", "pinyin": "chun yi", "quote": "一盘棋局，尽显春天智慧。" },
    "4-24": { "event": "春骑", "pinyin": "chun qi", "quote": "骑行春光里，感受速度与激情。" },
    "4-25": { "event": "春泳", "pinyin": "chun yong", "quote": "春水微温，畅游其中。" },
    "4-26": { "event": "春垂", "pinyin": "chun chui", "quote": "垂钓春水，静待鱼儿。" },
    "4-27": { "event": "春采", "pinyin": "chun cai", "quote": "采撷春天的馈赠。" },
    "4-28": { "event": "春烹", "pinyin": "chun peng", "quote": "烹饪春天的鲜美。" },
    "4-29": { "event": "春酿", "pinyin": "chun niang", "quote": "酿造春天的美酒。" },
    "4-30": { "event": "春馨", "pinyin": "chun xin", "quote": "春天的芬芳，沁人心脾。" },
// 5月
"5-1": {event: "劳动", pinyin: "lao dong", quote: "双手创造世界，汗水浇灌幸福。"},
"5-2": {event: "五一", pinyin: "wu yi", quote: "休憩是为了更好地前行。"},
"5-3": {event: "春游", pinyin: "chun you", quote: "春光不必趁早，但请勿虚度。"},
"5-4": {event: "青年", pinyin: "qing nian", quote: "青春如火，点燃理想的明灯。"},
"5-5": {event: "母亲", pinyin: "mu qin", quote: "母爱如水，润物细无声。"},
"5-6": {event: "护士", pinyin: "hu shi", quote: "白衣天使，用爱守护生命。"},
"5-7": {event: "防灾", pinyin: "fang zai", quote: "未雨绸缪，方能安然度日。"},
"5-8": {event: "微笑", pinyin: "wei xiao", quote: "微笑是最美的语言，跨越所有隔阂。"},
"5-9": {event: "立夏", pinyin: "li xia", quote: "夏至未至，但心已向阳。"},
"5-10": {event: "品茗", pinyin: "pin ming", quote: "一盏茶的时光，慢下来才是享受。"},
"5-11": {event: "防灾", pinyin: "fang zai", quote: "居安思危，才能化险为夷。"},
"5-12": {event: "护士", pinyin: "hu shi", quote: "仁心仁术，大爱无疆。"},
"5-13": {event: "母亲", pinyin: "mu qin", quote: "母爱是世间最伟大的力量。"},
"5-14": {event: "家庭", pinyin: "jia ting", quote: "家是避风港，也是动力源。"},
"5-15": {event: "家人", pinyin: "jia ren", quote: "亲情是生命中最温暖的阳光。"},
"5-16": {event: "和平", pinyin: "he ping", quote: "和平不是口号，是每个人的责任。"},
"5-17": {event: "电信", pinyin: "dian xin", quote: "信息连接世界，沟通拉近心灵。"},
"5-18": {event: "博物", pinyin: "bo wu", quote: "博物馆里，与历史对话。"},
"5-19": {event: "旅游", pinyin: "lv you", quote: "行走是最好的思考，旅行是最美的遇见。"},
"5-20": {event: "蜜蜂", pinyin: "mi feng", quote: "勤劳的蜜蜂，酿造生活的甜蜜。"},
"5-21": {event: "茶艺", pinyin: "cha yi", quote: "一片叶子的旅程，从山野到杯中。"},
"5-22": {event: "生物", pinyin: "sheng wu", quote: "生物多样性，是地球最美的彩妆。"},
"5-23": {event: "龟龄", pinyin: "gui ling", quote: "龟龄鹤寿，慢生活有长寿的智慧。"},
"5-24": {event: "文明", pinyin: "wen ming", quote: "文明如水，润物于无声处。"},
"5-25": {event: "尊严", pinyin: "zun yan", quote: "尊严不是施舍，而是与生俱来的权利。"},
"5-26": {event: "爱邻", pinyin: "ai lin", quote: "远亲不如近邻，邻里和睦是福。"},
"5-27": {event: "儿童", pinyin: "er tong", quote: "童心未泯，方能保持对世界的好奇。"},
"5-28": {event: "饥饿", pinyin: "ji e", quote: "珍惜粮食，感恩丰盈的生活。"},
"5-29": {event: "维和", pinyin: "wei he", quote: "和平需要守护，需要每个人的努力。"},
"5-30": {event: "禁烟", pinyin: "jin yan", quote: "戒烟不只为自己，也为爱你的人。"},
"5-31": {event: "无烟", pinyin: "wu yan", quote: "无烟生活，呼吸自由的空气。"},

// 6月
"6-1": {event: "儿童", pinyin: "er tong", quote: "童心如诗，童趣如画，童年如歌。"},
"6-2": {event: "长跑", pinyin: "chang pao", quote: "长跑如人生，坚持才能看到风景。"},
"6-3": {event: "爱耳", pinyin: "ai er", quote: "倾听世界，也倾听内心的声音。"},
"6-4": {event: "环保", pinyin: "huan bao", quote: "地球是我们唯一的家，珍爱它。"},
"6-5": {event: "环境", pinyin: "huan jing", quote: "保护环境，就是保护我们自己。"},
"6-6": {event: "眼睛", pinyin: "yan jing", quote: "用心去看，世界才会更美丽。"},
"6-7": {event: "食品", pinyin: "shi pin", quote: "食品安全，关乎每个人的健康。"},
"6-8": {event: "海洋", pinyin: "hai yang", quote: "海洋孕育生命，我们应当敬畏。"},
"6-9": {event: "档案", pinyin: "dang an", quote: "档案记录历史，也承载未来。"},
"6-10": {event: "文化", pinyin: "wen hua", quote: "文化是民族的灵魂，需要传承。"},
"6-11": {event: "人口", pinyin: "ren kou", quote: "人口红利，源于每个人的价值。"},
"6-12": {event: "儿童", pinyin: "er tong", quote: "童年的快乐，是一生的财富。"},
"6-13": {event: "小满", pinyin: "xiao man", quote: "小满不满，麦穗初齐，人生亦是。"},
"6-14": {event: "献血", pinyin: "xian xue", quote: "献血是爱的传递，生命的接力。"},
"6-15": {event: "风能", pinyin: "feng neng", quote: "风能是大自然的馈赠，取之不尽。"},
"6-16": {event: "父亲", pinyin: "fu qin", quote: "父爱如山，默默支撑起整个家。"},
"6-17": {event: "防治", pinyin: "fang zhi", quote: "防胜于治，健康源于日常。"},
"6-18": {event: "可持", pinyin: "ke chi", quote: "可持续发展，为子孙后代着想。"},
"6-19": {event: "爸爸", pinyin: "ba ba", quote: "父亲的肩膀，是孩子最安全的港湾。"},
"6-20": {event: "难民", pinyin: "nan min", quote: "同情难民，人道主义无国界。"},
"6-21": {event: "瑜伽", pinyin: "yu jia", quote: "瑜伽不只是姿势，更是生活态度。"},
"6-22": {event: "夏至", pinyin: "xia zhi", quote: "夏至阳盛，昼长夜短，珍惜光阴。"},
"6-23": {event: "奥运", pinyin: "ao yun", quote: "奥运精神：更快、更高、更强。"},
"6-24": {event: "帆船", pinyin: "fan chuan", quote: "扬帆起航，驶向梦想的彼岸。"},
"6-25": {event: "航海", pinyin: "hang hai", quote: "航海者的勇气，开拓未知的疆域。"},
"6-26": {event: "禁毒", pinyin: "jin du", quote: "珍爱生命，远离毒品。"},
"6-27": {event: "中小", pinyin: "zhong xiao", quote: "中小企业是经济的毛细血管。"},
"6-28": {event: "发明", pinyin: "fa ming", quote: "创新是民族进步的灵魂。"},
"6-29": {event: "渔民", pinyin: "yu min", quote: "渔民与海的对话，是生活的智慧。"},
"6-30": {event: "小暑", pinyin: "xiao shu", quote: "小暑已至，热浪初显，静待花开。"},

// 7月
"7-1": {event: "建党", pinyin: "jian dang", quote: "不忘初心，方得始终。"},
"7-2": {event: "体育", pinyin: "ti yu", quote: "体育精神，超越自我，挑战极限。"},
"7-3": {event: "炎热", pinyin: "yan re", quote: "炎炎夏日，静待秋风至。"},
"7-4": {event: "独立", pinyin: "du li", quote: "独立思考是最珍贵的能力。"},
"7-5": {event: "合作", pinyin: "he zuo", quote: "合作共赢，是最高明的智慧。"},
"7-6": {event: "接吻", pinyin: "jie wen", quote: "一个吻，是心与心的对话。"},
"7-7": {event: "七夕", pinyin: "qi xi", quote: "鹊桥相会，爱情的美丽传说。"},
"7-8": {event: "读书", pinyin: "du shu", quote: "书籍是人类进步的阶梯。"},
"7-9": {event: "禁忧", pinyin: "jin you", quote: "忧从心上起，解从心上灭。"},
"7-10": {event: "集邮", pinyin: "ji you", quote: "邮票是历史的缩影，文化的载体。"},
"7-11": {event: "人口", pinyin: "ren kou", quote: "人口质量，决定国家未来。"},
"7-12": {event: "航海", pinyin: "hang hai", quote: "扬帆远航，不畏风浪。"},
"7-13": {event: "少年", pinyin: "shao nian", quote: "少年强则国强，少年智则国智。"},
"7-14": {event: "交流", pinyin: "jiao liu", quote: "交流碰撞，思想的火花才会迸发。"},
"7-15": {event: "青年", pinyin: "qing nian", quote: "青年兴则国家兴，青年强则国家强。"},
"7-16": {event: "蛇类", pinyin: "she lei", quote: "敬畏自然，尊重生命。"},
"7-17": {event: "司法", pinyin: "si fa", quote: "公平正义，是社会的基石。"},
"7-18": {event: "尼尔", pinyin: "ni er", quote: "一小步，一大步，人类的伟大跨越。"},
"7-19": {event: "朋友", pinyin: "peng you", quote: "朋友如酒，越久越醇。"},
"7-20": {event: "棋艺", pinyin: "qi yi", quote: "棋如人生，落子无悔。"},
"7-21": {event: "泳池", pinyin: "yong chi", quote: "畅游水中，感受自由的快乐。"},
"7-22": {event: "脑部", pinyin: "nao bu", quote: "大脑是人体最神奇的器官。"},
"7-23": {event: "大暑", pinyin: "da shu", quote: "大暑酷热，静心避暑。"},
"7-24": {event: "表弟", pinyin: "biao di", quote: "亲情是生命中最温暖的阳光。"},
"7-25": {event: "防溺", pinyin: "fang ni", quote: "安全第一，珍爱生命。"},
"7-26": {event: "语言", pinyin: "yu yan", quote: "语言是思想的外衣，文化的载体。"},
"7-27": {event: "跳伞", pinyin: "tiao san", quote: "勇敢跳下，才能感受自由落体的快感。"},
"7-28": {event: "肝炎", pinyin: "gan yan", quote: "健康是1，其他是后面的0。"},
"7-29": {event: "老虎", pinyin: "lao hu", quote: "敬畏自然，保护野生动物。"},
"7-30": {event: "友谊", pinyin: "you yi", quote: "友谊如茶，淡而长久。"},
"7-31": {event: "非洲", pinyin: "fei zhou", quote: "非洲是人类的摇篮，文明的起源。"},

// 8月
"8-1": {event: "建军", pinyin: "jian jun", quote: "军人的担当，守护和平的力量。"},
"8-2": {event: "电影", pinyin: "dian ying", quote: "电影是光影的艺术，情感的载体。"},
"8-3": {event: "男人", pinyin: "nan ren", quote: "男人的担当，是家庭的脊梁。"},
"8-4": {event: "同事", pinyin: "tong shi", quote: "同事情谊，职场中的温暖。"},
"8-5": {event: "啤酒", pinyin: "pi jiu", quote: "啤酒配烧烤，夏日的小确幸。"},
"8-6": {event: "和平", pinyin: "he ping", quote: "和平是人类最宝贵的财富。"},
"8-7": {event: "立秋", pinyin: "li qiu", quote: "立秋虽至，暑气未消。"},
"8-8": {event: "全民", pinyin: "quan min", quote: "全民健身，健康中国。"},
"8-9": {event: "土著", pinyin: "tu zhu", quote: "尊重多元文化，保护原住民权益。"},
"8-10": {event: "狮子", pinyin: "shi zi", quote: "狮子是草原之王，象征勇气与力量。"},
"8-11": {event: "慢车", pinyin: "man che", quote: "慢一点，欣赏沿途的风景。"},
"8-12": {event: "青年", pinyin: "qing nian", quote: "青春无悔，奋斗不止。"},
"8-13": {event: "左撇", pinyin: "zuo pie", quote: "左撇子的世界，同样精彩。"},
"8-14": {event: "慰安", pinyin: "wei an", quote: "铭记历史，珍爱和平。"},
"8-15": {event: "空军", pinyin: "kong jun", quote: "翱翔蓝天，守护祖国的蓝天。"},
"8-16": {event: "漫画", pinyin: "man hua", quote: "漫画是童年的记忆，成长的陪伴。"},
"8-17": {event: "医师", pinyin: "yi shi", quote: "医者仁心，救死扶伤。"},
"8-18": {event: "人道", pinyin: "ren dao", quote: "人道主义精神，超越国界的关怀。"},
"8-19": {event: "摄影", pinyin: "she ying", quote: "摄影是用光与影讲述的故事。"},
"8-20": {event: "蚊子", pinyin: "wen zi", quote: "小小蚊子，也是生态链的一环。"},
"8-21": {event: "老人", pinyin: "lao ren", quote: "尊老敬老，是中华民族的传统美德。"},
"8-22": {event: "植物", pinyin: "zhi wu", quote: "植物是地球的肺，守护它们。"},
"8-23": {event: "奴隶", pinyin: "nu li", quote: "铭记历史，珍视自由与平等。"},
"8-24": {event: "公园", pinyin: "gong yuan", quote: "公园是城市的绿肺，市民的氧吧。"},
"8-25": {event: "残奥", pinyin: "can ao", quote: "残奥精神：超越自我，挑战极限。"},
"8-26": {event: "全国", pinyin: "quan guo", quote: "法治社会，人人平等。"},
"8-27": {event: "旅游", pinyin: "lv you", quote: "旅行不在远近，而在于心情。"},
"8-28": {event: "测量", pinyin: "ce liang", quote: "精确测量，科学发展的基础。"},
"8-29": {event: "禁核", pinyin: "jin he", quote: "无核世界，和平共处。"},
"8-30": {event: "慈善", pinyin: "ci shan", quote: "慈善是心灵的阳光，温暖他人。"},
"8-31": {event: "野生", pinyin: "ye sheng", quote: "保护野生动物，维护生态平衡。"},

// 9月
"9-1": {event: "开学", pinyin: "kai xue", quote: "新学期，新起点，新希望。"},
"9-2": {event: "抗战", pinyin: "kang zhan", quote: "铭记历史，珍爱和平。"},
"9-3": {event: "抗日", pinyin: "kang ri", quote: "勿忘国耻，振兴中华。"},
"9-4": {event: "公报", pinyin: "gong bao", quote: "信息透明，民主法治的基石。"},
"9-5": {event: "慈善", pinyin: "ci shan", quote: "慈善是心灵的阳光，温暖他人。"},
"9-6": {event: "维和", pinyin: "wei he", quote: "维和部队，和平的使者。"},
"9-7": {event: "白露", pinyin: "bai lu", quote: "白露秋分夜，一夜冷一夜。"},
"9-8": {event: "扫盲", pinyin: "sao mang", quote: "知识改变命运，教育点亮人生。"},
"9-9": {event: "教师", pinyin: "jiao shi", quote: "春蚕到死丝方尽，蜡炬成灰泪始干。"},
"9-10": {event: "预防", pinyin: "yu fang", quote: "预防胜于治疗，健康源于生活。"},
"9-11": {event: "中秋", pinyin: "zhong qiu", quote: "但愿人长久，千里共婵娟。"},
"9-12": {event: "程序", pinyin: "cheng xu", quote: "代码改变世界，创新驱动未来。"},
"9-13": {event: "体育", pinyin: "ti yu", quote: "体育强国，健康中国。"},
"9-14": {event: "烈士", pinyin: "lie shi", quote: "英雄不朽，精神永存。"},
"9-15": {event: "臭氧", pinyin: "chou yang", quote: "保护臭氧层，守护地球家园。"},
"9-16": {event: "民主", pinyin: "min zhu", quote: "民主法治，公平正义。"},
"9-17": {event: "和平", pinyin: "he ping", quote: "和平发展，共创未来。"},
"9-18": {event: "九一", pinyin: "jiu yi", quote: "勿忘国耻，自强不息。"},
"9-19": {event: "中国", pinyin: "zhong guo", quote: "五谷丰登，国泰民安。"},
"9-20": {event: "爱牙", pinyin: "ai ya", quote: "牙齿健康，全身健康。"},
"9-21": {event: "和平", pinyin: "he ping", quote: "和平不是口号，是每个人的责任。"},
"9-22": {event: "无车", pinyin: "wu che", quote: "绿色出行，低碳环保。"},
"9-23": {event: "秋分", pinyin: "qiu fen", quote: "秋分时节，昼夜均分。"},
"9-24": {event: "聋人", pinyin: "long ren", quote: "无声世界，同样精彩。"},
"9-25": {event: "旅游", pinyin: "lv you", quote: "行走是最好的思考，旅行是最美的遇见。"},
"9-26": {event: "世界", pinyin: "shi jie", quote: "科学避孕，幸福生活。"},
"9-27": {event: "旅游", pinyin: "lv you", quote: "行走天下，开阔视野。"},
"9-28": {event: "教师", pinyin: "jiao shi", quote: "教师是人类灵魂的工程师。"},
"9-29": {event: "心脏", pinyin: "xin zang", quote: "心脏健康，生命之源。"},
"9-30": {event: "烈士", pinyin: "lie shi", quote: "缅怀先烈，不忘初心。"},

// 10月
"10-1": {event: "国庆", pinyin: "guo qing", quote: "祖国繁荣昌盛，人民幸福安康。"},
"10-2": {event: "老人", pinyin: "lao ren", quote: "尊老敬老，是中华民族的传统美德。"},
"10-3": {event: "国庆", pinyin: "guo qing", quote: "祖国在我心中，如同灯塔指引方向。"},
"10-4": {event: "世界", pinyin: "shi jie", quote: "爱护动物，就是爱护我们共同的家园。"},
"10-5": {event: "教师", pinyin: "jiao shi", quote: "教师如蜡烛，燃烧自己，照亮他人。"},
"10-6": {event: "志愿", pinyin: "zhi yuan", quote: "志愿服务，传递爱的温度。"},
"10-7": {event: "住房", pinyin: "zhu fang", quote: "安居才能乐业，家是最温暖的港湾。"},
"10-8": {event: "邮政", pinyin: "you zheng", quote: "邮递员是爱的传递者，连接世界的桥梁。"},
"10-9": {event: "寒露", pinyin: "han lu", quote: "寒露时节，秋意渐浓。"},
"10-10": {event: "精神", pinyin: "jing shen", quote: "心灵的阳光，照亮内心的角落。"},
"10-11": {event: "女孩", pinyin: "nv hai", quote: "女孩如花，需要全社会的呵护。"},
"10-12": {event: "减灾", pinyin: "jian zai", quote: "防患于未然，减轻灾害损失。"},
"10-13": {event: "保健", pinyin: "bao jian", quote: "勤洗手，远离病菌，健康生活。"},
"10-14": {event: "标准", pinyin: "biao zhun", quote: "标准化让生活更美好，品质更可靠。"},
"10-15": {event: "盲人", pinyin: "mang ren", quote: "心中有光明，何惧眼前黑暗。"},
"10-16": {event: "粮食", pinyin: "liang shi", quote: "粒粒皆辛苦，珍惜来之不易的粮食。"},
"10-17": {event: "扶贫", pinyin: "fu pin", quote: "扶贫先扶志，授人以渔胜于授人以鱼。"},
"10-18": {event: "医疗", pinyin: "yi liao", quote: "健康是人生最宝贵的财富。"},
"10-19": {event: "统计", pinyin: "tong ji", quote: "数据背后，是生活的真相。"},
"10-20": {event: "骨质", pinyin: "gu zhi", quote: "强健骨骼，从日常做起。"},
"10-21": {event: "节约", pinyin: "jie yue", quote: "节约用水，滴水之恩当涌泉相报。"},
"10-22": {event: "使馆", pinyin: "shi guan", quote: "外交使节，架起友谊的桥梁。"},
"10-23": {event: "联合", pinyin: "lian he", quote: "联合国精神：和平、发展、合作。"},
"10-24": {event: "程序", pinyin: "cheng xu", quote: "代码改变世界，创新驱动未来。"},
"10-25": {event: "台风", pinyin: "tai feng", quote: "防范台风，安全第一。"},
"10-26": {event: "节俭", pinyin: "jie jian", quote: "勤俭节约，是中华民族的传统美德。"},
"10-27": {event: "冬至", pinyin: "dong zhi", quote: "冬至一阳生，希望在前方。"},
"10-28": {event: "动画", pinyin: "dong hua", quote: "动画是童年的记忆，成长的陪伴。"},
"10-29": {event: "互联", pinyin: "hu lian", quote: "互联网连接世界，也连接心灵。"},
"10-30": {event: "节俭", pinyin: "jie jian", quote: "节约是美德，浪费是可耻的。"},
"10-31": {event: "万圣", pinyin: "wan sheng", quote: "万圣节的童趣，唤醒内心的童真。"},

// 11月
"11-1": {event: "万圣", pinyin: "wan sheng", quote: "童心未泯，才能感受节日的快乐。"},
"11-2": {event: "追思", pinyin: "zhui si", quote: "缅怀逝者，珍惜当下。"},
"11-3": {event: "文明", pinyin: "wen ming", quote: "文明礼貌，从小事做起。"},
"11-4": {event: "宪法", pinyin: "xian fa", quote: "宪法是国家的根本大法，人人须遵守。"},
"11-5": {event: "爱子", pinyin: "ai zi", quote: "爱子不宠溺，严中有爱才是真爱。"},
"11-6": {event: "立冬", pinyin: "li dong", quote: "立冬时节，添衣保暖。"},
"11-7": {event: "科学", pinyin: "ke xue", quote: "科学技术是第一生产力。"},
"11-8": {event: "记者", pinyin: "ji zhe", quote: "记者是真相的守护者，社会的良心。"},
"11-9": {event: "消防", pinyin: "xiao fang", quote: "防患于未然，消防安全记心间。"},
"11-10": {event: "青年", pinyin: "qing nian", quote: "青年兴则国家兴，青年强则国家强。"},
"11-11": {event: "光棍", pinyin: "guang gun", quote: "单身的自由，也是一种幸福。"},
"11-12": {event: "健康", pinyin: "jian kang", quote: "健康的身体是革命的本钱。"},
"11-13": {event: "爱眼", pinyin: "ai yan", quote: "明亮的双眼，是心灵的窗户。"},
"11-14": {event: "糖尿", pinyin: "tang niao", quote: "控制血糖，健康生活。"},
"11-15": {event: "回收", pinyin: "hui shou", quote: "垃圾分类，变废为宝。"},
"11-16": {event: "宽容", pinyin: "kuan rong", quote: "宽容是一种美德，也是一种智慧。"},
"11-17": {event: "学生", pinyin: "xue sheng", quote: "学生时代，是人生最美好的时光。"},
"11-18": {event: "禁烟", pinyin: "jin yan", quote: "吸烟有害健康，远离香烟。"},
"11-19": {event: "厕所", pinyin: "ce suo", quote: "厕所革命，文明如厕。"},
"11-20": {event: "儿童", pinyin: "er tong", quote: "儿童是祖国的花朵，民族的希望。"},
"11-21": {event: "问候", pinyin: "wen hou", quote: "一声问候，温暖一整天。"},
"11-22": {event: "感恩", pinyin: "gan en", quote: "感恩之心，常存于心。"},
"11-23": {event: "小雪", pinyin: "xiao xue", quote: "小雪纷飞，冬意渐浓。"},
"11-24": {event: "遗产", pinyin: "yi chan", quote: "文化遗产，是民族的根脉。"},
"11-25": {event: "消除", pinyin: "xiao chu", quote: "消除暴力，构建和谐社会。"},
"11-26": {event: "环保", pinyin: "huan bao", quote: "保护环境，人人有责。"},
"11-27": {event: "教师", pinyin: "jiao shi", quote: "教师是太阳底下最光辉的职业。"},
"11-28": {event: "感恩", pinyin: "gan en", quote: "感恩生活中的每一个人，每一件事。"},
"11-29": {event: "援助", pinyin: "yuan zhu", quote: "伸出援手，传递温暖。"},
"11-30": {event: "电脑", pinyin: "dian nao", quote: "电脑安全，信息保护。"},

// 12月
"12-1": {event: "艾滋", pinyin: "ai zi", quote: "关爱艾滋病患者，消除歧视与偏见。"},
"12-2": {event: "交通", pinyin: "jiao tong", quote: "文明出行，安全第一。"},
"12-3": {event: "残疾", pinyin: "can ji", quote: "平等对待残疾人，共建包容社会。"},
"12-4": {event: "宪法", pinyin: "xian fa", quote: "宪法是国家的根本大法，人人须遵守。"},
"12-5": {event: "志愿", pinyin: "zhi yuan", quote: "志愿服务，传递爱的温度。"},
"12-6": {event: "交通", pinyin: "jiao tong", quote: "安全出行，文明交通。"},
"12-7": {event: "大雪", pinyin: "da xue", quote: "大雪纷飞，银装素裹。"},
"12-8": {event: "气象", pinyin: "qi xiang", quote: "关注气象，安全生活。"},
"12-9": {event: "足球", pinyin: "zu qiu", quote: "足球不只是运动，更是一种精神。"},
"12-10": {event: "人权", pinyin: "ren quan", quote: "尊重人权，人人平等。"},
"12-11": {event: "山岳", pinyin: "shan yue", quote: "山高水长，自然之美令人敬畏。"},
"12-12": {event: "西安", pinyin: "xi an", quote: "铭记历史，勿忘国耻。"},
"12-13": {event: "南京", pinyin: "nan jing", quote: "南京大屠杀，民族的伤痛记忆。"},
"12-14": {event: "能源", pinyin: "neng yuan", quote: "节约能源，绿色生活。"},
"12-15": {event: "改革", pinyin: "gai ge", quote: "改革开放，中国腾飞的动力。"},
"12-16": {event: "反腐", pinyin: "fan fu", quote: "反腐倡廉，建设清明政治。"},
"12-17": {event: "航天", pinyin: "hang tian", quote: "仰望星空，探索未知的宇宙。"},
"12-18": {event: "移民", pinyin: "yi min", quote: "尊重移民，多元文化共存。"},
"12-19": {event: "救助", pinyin: "jiu zhu", quote: "伸出援手，温暖他人。"},
"12-20": {event: "澳门", pinyin: "ao men", quote: "澳门回归，祖国统一的历史时刻。"},
"12-21": {event: "篮球", pinyin: "lan qiu", quote: "篮球场上的拼搏，人生的缩影。"},
"12-22": {event: "冬至", pinyin: "dong zhi", quote: "冬至阳生春又来，新的希望在前方。"},
"12-23": {event: "平安", pinyin: "ping an", quote: "平安夜的祝福，传递温暖与关爱。"},
"12-24": {event: "圣诞", pinyin: "sheng dan", quote: "圣诞节的欢乐，跨越文化的界限。"},
"12-25": {event: "宪法", pinyin: "xian fa", quote: "宪法日，法治中国的基石。"},
"12-26": {event: "感恩", pinyin: "gan en", quote: "感恩的心，感谢有你。"},
"12-27": {event: "资源", pinyin: "zi yuan", quote: "珍惜资源，可持续发展。"},
"12-28": {event: "安全", pinyin: "an quan", quote: "安全生产，人人有责。"},
"12-29": {event: "生物", pinyin: "sheng wu", quote: "生物多样性，地球生命的财富。"},
"12-30": {event: "保护", pinyin: "bao hu", quote: "保护环境，就是保护我们自己。"},
"12-31": {event: "跨年", pinyin: "kua nian", quote: "辞旧迎新，展望美好未来。"}
};